eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
        server:
          webflux:
            routes:
              - id: user-service
                uri: lb://USER-SERVICE
                predicates:
                  - name: Path
                    args:
                      pattern: /user-service/**

              - id: security-service
                uri: lb://SECURITY-SERVICE
                predicates:
                  - name: Path
                    args:
                      pattern: /security-service/**

              - id: vehicle-service
                uri: lb://VEHICLE-SERVICE
                predicates:
                  - name: Path
                    args:
                      pattern: /vehicle-service/**
