server:
  port: 8083

spring:
  application:
    name: parking-space-service
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true