server:
  port: 8081
#  servlet:
#    context-path: /user-service

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  instance:
    hostname: localhost

jwt:
  secret: "4351cf1fc73a5438049070432d273ca79c5e6109eca76642667d0ff3b6d80d9419cfc66353bfe0ee7197f47a267383fccac12c9f8fc5cf0bbf4277115319618d"