server:
  port: 8888

spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Tharidi2002/SPMS-config-repo.git
#          default-label: master
  application:
    name: config-server